const data = [
  {
    key: "1",
    assetId: "83028",
    color: "blue",
    // client: "Blue Corp",
    // dest: "Jaydev vihar",
    lat: pointAData.latitude.toFixed(4),
    long: pointAData.longitude.toFixed(4),
  },
  {
    key: "2",
    assetId: "82541",
    color: "red",
    // client: "Red Corp",
    // dest: "Jaydev vihar",
    lat: pointBData.latitude.toFixed(4),
    long: pointBData.longitude.toFixed(4),
  },
  {
    key: "3",
    assetId: "9631",
    color: "red",
    // client: "Red Corp",
    // dest: "Jaydev vihar",
    lat: (Math.random() * 100).toFixed(4),
    long: (Math.random() * 100).toFixed(4),
  },
  {
    key: "3",
    assetId: "9631",
    color: "red",
    // client: "Red Corp",
    // dest: "Jaydev vihar",
    lat: (Math.random() * 100).toFixed(4),
    long: (Math.random() * 100).toFixed(4),
  },
  {
    key: "3",
    assetId: "9631",
    color: "red",
    // client: "Red Corp",
    // dest: "Jaydev vihar",
    lat: (Math.random() * 100).toFixed(4),
    long: (Math.random() * 100).toFixed(4),
  },
  {
    key: "3",
    assetId: "9631",
    color: "red",
    // client: "Red Corp",
    // dest: "Jaydev vihar",
    lat: (Math.random() * 100).toFixed(4),
    long: (Math.random() * 100).toFixed(4),
  },
  {
    key: "3",
    assetId: "9631",
    color: "red",
    // client: "Red Corp",
    // dest: "Jaydev vihar",
    lat: (Math.random() * 100).toFixed(4),
    long: (Math.random() * 100).toFixed(4),
  },
  {
    key: "3",
    assetId: "9631",
    color: "red",
    // client: "Red Corp",
    // dest: "Jaydev vihar",
    lat: (Math.random() * 100).toFixed(4),
    long: (Math.random() * 100).toFixed(4),
  },
  {
    key: "3",
    assetId: "9631",
    color: "red",
    // client: "Red Corp",
    // dest: "Jaydev vihar",
    lat: (Math.random() * 100).toFixed(4),
    long: (Math.random() * 100).toFixed(4),
  },
  {
    key: "3",
    assetId: "9631",
    color: "red",
    // client: "Red Corp",
    // dest: "Jaydev vihar",
    lat: (Math.random() * 100).toFixed(4),
    long: (Math.random() * 100).toFixed(4),
  },
];
